name: deploy-project

on:
    pull_request:
        types: [opened, closed]
        branches: [develop, main]
    workflow_dispatch:

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2

            - name: Install Dependencies
              run: npm install

            - name: Build
              run: npm build

            - name: Test
              run: npm test
