name: deploy-project

on:
    pull_request:
        branches: [develop, main]
    workflow_dispatch:

jobs:
    build:
        runs-on: ubuntu-latest
        env:
            working-directory: ./frontend
        steps:
            - uses: actions/checkout@v4

            - name: Install Dependencies
              run: npm install
              working-directory: ./frontend

            - name: Build
              run: npm build
              working-directory: ./frontend

            - name: Test
              run: npm test
              working-directory: ./frontend

            - uses: hkusu/review-assign-action@v1
              with:
                  assignees: ${{ github.actor }} # assign pull request author
                  reviewers: mingnana # if draft, assigned when draft is released
